### PR TITLE
Changed properties format

### PR DESCRIPTION
**Pull request by smolvik1**

### CODE REVIEW

**Comment by knudsvik** [comment]
@smolvik1 Looks like the travis tests are not running, do you know why?

**Comment by smolvik1** [comment]
Travis-ci has commersialized. From .org to .com and now requires a priced subscription.

**Comment by knudsvik** [comment]
Maybe it should be replaced with Github Actions?

**Comment by smolvik1** [comment]
Will close and re-submit this PR to see that pytests are running

**Pull request closed without merging**
